/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.AF2PMain.AF2PView;
import Views.AFDMain.AFDView;
import Views.AFPDMain.AFPDView;
import Views.AFPNMain.AFPNView;
import Views.MTMCMain.MTMCView;
import Views.MTMain.MTView;
import Views.MTPMain.MTPView;
import java.text.ParseException;

/**
 *
 * @author aleja
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afdButton = new javax.swing.JButton();
        afpdButton = new javax.swing.JButton();
        afpnButton = new javax.swing.JButton();
        af2pButton = new javax.swing.JButton();
        mtButton = new javax.swing.JButton();
        mtpButton = new javax.swing.JButton();
        mtmcButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        afdButton.setText("AFD");
        afdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afdButtonActionPerformed(evt);
            }
        });

        afpdButton.setText("AFPD");
        afpdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afpdButtonActionPerformed(evt);
            }
        });

        afpnButton.setText("AFPN");
        afpnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afpnButtonActionPerformed(evt);
            }
        });

        af2pButton.setText("AF2P");
        af2pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                af2pButtonActionPerformed(evt);
            }
        });

        mtButton.setText("MT");
        mtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtButtonActionPerformed(evt);
            }
        });

        mtpButton.setText("MTP");
        mtpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtpButtonActionPerformed(evt);
            }
        });

        mtmcButton.setText("MTMC");
        mtmcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtmcButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Proyecto Introducción a la Teoría de la Computación");

        jLabel2.setText("Por favor, escoja uno de los autómatas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(afpnButton)
                                .addGap(136, 136, 136)
                                .addComponent(mtmcButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(af2pButton)
                                    .addComponent(afdButton))
                                .addGap(137, 137, 137)
                                .addComponent(mtButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(afpdButton)
                                .addGap(136, 136, 136)
                                .addComponent(mtpButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addGap(20, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mtButton)
                    .addComponent(afdButton))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mtpButton)
                            .addComponent(afpdButton))
                        .addGap(18, 18, 18)
                        .addComponent(mtmcButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addComponent(afpnButton)
                        .addGap(18, 18, 18)
                        .addComponent(af2pButton)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afdButtonActionPerformed
        AFDView afdView = new AFDView();
        afdView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_afdButtonActionPerformed

    private void afpdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afpdButtonActionPerformed
        AFPDView afpdView = new AFPDView();
        afpdView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_afpdButtonActionPerformed

    private void afpnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afpnButtonActionPerformed
        AFPNView afpnView = new AFPNView();
        afpnView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_afpnButtonActionPerformed

    private void af2pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_af2pButtonActionPerformed
        AF2PView af2PView = new AF2PView();
        af2PView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_af2pButtonActionPerformed

    private void mtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtButtonActionPerformed
        MTView mtView = new MTView();
        mtView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mtButtonActionPerformed

    private void mtpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtpButtonActionPerformed
        MTPView mtpView = new MTPView();
        mtpView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mtpButtonActionPerformed

    private void mtmcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtmcButtonActionPerformed
        MTMCView mtmcView = new MTMCView();
        mtmcView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mtmcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton af2pButton;
    private javax.swing.JButton afdButton;
    private javax.swing.JButton afpdButton;
    private javax.swing.JButton afpnButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mtButton;
    private javax.swing.JButton mtmcButton;
    private javax.swing.JButton mtpButton;
    // End of variables declaration//GEN-END:variables
}
